name: Update Hashes
on:
  workflow_dispatch:
  push:
    paths:
      - 'strategies/byedpi/strategy-*.txt'
      - 'strategies/nfqws/strategy-*.txt'
      - 'lists/include/list-*.txt'
      - 'lists/exclude/list-*.txt'

jobs:
  update-hashes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Update hashes and clean entries
      run: |
        set -e
        calc_hash() { sha256sum "$1" | awk '{print $1}'; }
        make_url() { echo "https://raw.githubusercontent.com/CherretGit/zaprett-repo/main/$1"; }
        process_files() {
          local folder="$1"
          local pattern="$2"
          local json="$3"
          find "$folder" -name "$pattern" -type f | while read -r file; do
            filename=$(basename "$file")
            dir=$(basename "$(dirname "$file")")
            if [ "$dir" = "exclude" ]; then
              type="list_exclude"
            else
              type="$dir"
            fi
            if jq -e --arg name "$filename" '.[] | select(.name == $name)' "$json" >/dev/null; then
              hash=$(calc_hash "$file")
              jq --arg name "$filename" --arg hash "$hash" '
                map(if .name == $name then .hash = $hash else . end)
              ' "$json" > tmp.json && mv tmp.json "$json"
            else
              hash=$(calc_hash "$file")
              url=$(make_url "$file")
              jq --arg name "$filename" --arg hash "$hash" --arg url "$url" --arg type "$type" '
                . + [{
                  name: $name,
                  author: "не указано",
                  description: "не указано",
                  hash: $hash,
                  type: $type,
                  url: $url
                }]
              ' "$json" > tmp.json && mv tmp.json "$json"
            fi
          done
        }
        process_files "strategies" "strategy-*.txt" "strategies.json"
        process_files "lists" "list-*.txt" "hosts.json"
        for json in hosts.json strategies.json; do
          [ -f "$json" ] || continue
          case "$json" in
            "hosts.json")
              folder="lists"
              pattern="list-*.txt"
              ;;
            "strategies.json")
              folder="strategies"
              pattern="strategy-*.txt"
              ;;
          esac
          existing_files=$(find "$folder" -name "$pattern" -type f -exec basename {} \;)
          jq --argjson existing "$(printf '%s\n' $existing_files | jq -R -s 'split("\n")[:-1]')" '
            map(select(.name as $n | $existing | index($n)))
          ' "$json" > tmp.json && mv tmp.json "$json"
        done

    - name: Show diff
      run: git diff

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Автообновление: хэши, новые записи, очистка"
        file_pattern: 'hosts.json strategies.json'

